export enum Classes {
  Berserker = "Berserker",
  Paladin = "Paladin",
  Gunlancer = "Gunlancer",
  Destroyer = "Destroyer",
  Striker = "Striker",
  Wardancer = "Wardancer",
  Scrapper = "Scrapper",
  Soulfist = "Soulfist",
  Glaivier = "Glaivier",
  Gunslinger = "Gunslinger",
  Artillerist = "Artillerist",
  Deadeye = "Deadeye",
  Sharpshooter = "Sharpshooter",
  Machinist = "Machinist",
  Bard = "Bard",
  Sorceress = "Sorceress",
  Arcanist = "Arcanist",
  Shadowhunter = "Shadowhunter",
  Deathblade = "Deathblade",
  Reaper = "Reaper",
}
